### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by muradabdulrahman** [merve-kaftancioglu/GWSTA-#1]
**Title of the manuscript:** Epigenetic differences of Retromer proteins for immune cells in Multiple Sclerosis

**Author:** Merve Kaftancioglu
**Reviwer** Abdulrahman Murad

### 1. Summary of the Research

Merve's manuscript delves into the study of epigenetic modifications in retromer proteins within immune cells of Multiple Sclerosis (MS) patients, focusing on CD4+ T cells, CD8+ T cells, B cells, and NK cells. The research aims to shed light on the epigenetic landscape that could potentially influence the functionality of immune cells in MS, which is a novel approach to understanding the disease's pathogenesis.

#### Overall Impression
The study is methodologically sound, with a clear focus and well-established experimental design. The choice of investigating retromer proteins is particularly notable due to their less explored role in immune function within the context of MS. The manuscript is nicely written, However, it does suffer from significant issues related to data presentation and statistical analysis. Additionally, the manuscript details the challenges faced by the author in executing the experimental pipeline. Despite numerous attempts using various alignment tools, the author was unable to successfully complete the critical alignment step. This failure has resulted in the absence of preliminary results, which is a crucial setback for the study's progress and conclusions. These difficulties should be addressed to enhance the manuscript's impact and ensure the reliability of the findings. 

### Major Issues

1. **Alignment Tool Failure**: The author faced significant challenges with alignment tools, which are critical for the success of bioinformatics pipelines. Despite numerous attempts using different tools, the alignment step could not be successfully completed, leading to the absence of preliminary results. This issue is crucial as it directly impacts the ability to proceed with further analyses and obtain meaningful outcomes.

2. **Batch Script Generation**: The author reports difficulties in generating batch scripts due to the incompatibility of tool-specific code patterns. Relying solely on Python or R proved to be a limitation, necessitating the use of AI services like Gemini and Copilot for script correction and improvement. Using such AI tools can be of great help but it won't often solve the problem if the one dealing with the data is uncomfortable with such tools and pipelines. 

3. **Tool Evaluation and Selection**: There is a noted challenge in evaluating and selecting the right tools for specific tasks within the project. The author highlights the necessity of feedback from experienced individuals and the importance of comparing tools to understand their strengths and weaknesses. This suggests that the project could benefit from a more structured approach to tool selection and evaluation.

### Minor Issues

1. **Methodology Presentation**: The methodology section in the report primarily consists of a list of steps and tools used, which lacks depth in explaining the procedural aspects of the research. While it's good practice to detail the tools and their versions, such as FastQC v0.11.7, BWA v0.7.17, and Docker v.26.1.2, merely listing these does not provide a comprehensive understanding of the methods applied. Even though, that detailed code documentation is available in a separate file, `method.md`. It is advisable to integrate key elements of this documentation directly into the main report to provide a cohesive and comprehensive methodological narrative. This integration would help readers understand not only what tools were used but also how they were applied in the context of the research, enhancing the reproducibility and clarity of the study.
2. **The Dataset**: It would have been beneficial, and in my opinion, crucial to represent the dataset used in a table format. Detailing the different datasets, including how many control and treated samples were used, would provide clarity and aid in understanding the scope and scale of the study. This presentation could help readers quickly grasp the experimental design and validate the results more effectively.

**Comment by merve-kaftancioglu** [comment]
https://github.com/SUcompBio/gwsta-2024-project-muradabdulrahman/issues/10
